version: '3.8'

services:
  django:
    volumes:
      - app:/usr/src/app
    build: .
    container_name:
      django
    ports:
      - 8000:8000
    restart: unless-stopped
    command:
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    volumes:
      - pg:/var/lib/postgresql/data
    image: postgres:14.7-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=worker
      - POSTGRES_PASSWORD=worker
    container_name:
      db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worker -d app"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  app:
  pg: